alfamas/views.py
# -*- coding: utf-8 -*-

from functools import wraps
from sqlalchemy import asc, desc
from flask import Blueprint, redirect, url_for, current_app, request, flash, Response
from flask_login import current_user, login_user, logout_user
from flask_babelplus import gettext as _
from flask_allows import Permission, And
from flaskbb.extensions import db, allows, csrf
from flaskbb.utils.settings import flaskbb_config
from flaskbb.utils.helpers import (
    get_online_users, time_diff, format_quote, render_template, do_topic_action
)

from flaskbb.utils.requirements import (
    CanAccessForum,
    CanAccessTopic,
    CanDeletePost,
    CanDeleteTopic,
    CanEditPost,
    CanPostReply,
    CanPostTopic,
    IsAtleastModeratorInForum,
)
from flaskbb.forum.models import (
    Category, Forum, Topic, Post, ForumsRead, TopicsRead
)
from flaskbb.forum.forms import (
    NewTopicForm,
    QuickreplyForm,
    ReplyForm,
    ReportForm,
    SearchPageForm,
    UserSearchForm,
)

from flaskbb.user.models import User

import datetime
import json

alfamas = Blueprint(
    "alfamas", 
    __name__, 
    #subdomain="foros",
    template_folder="templates",
    static_folder='static'
)

RESIDENTES_URL = "http://residentes.naifo.org"

@alfamas.context_processor
def inject_residentes_url():
    return dict(residentes_url=RESIDENTES_URL)

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if current_user is not None and current_user.is_authenticated:
            return f(*args, **kwargs)

        else:
            return redirect(url_for("alfamas.index"))

    return decorated

@alfamas.route("/")
def index():
    return redirect(RESIDENTES_URL)

@alfamas.route("/<forum>/login/<username>/<password>")
def login(forum, username, password):

    user, authenticated = User.authenticate(username, password)

    if user and authenticated:
        login_user(user)

    return redirect('/alfamas/%s' % forum)
    
@alfamas.route("/logout")
@login_required
def logout():
    logout_user()
    print "logout"
    return redirect(RESIDENTES_URL+"/logout")

@csrf.exempt
@alfamas.route("/register", methods=['PUT'])
def register():

    username = request.form['username']
    password = request.form['password']
    firstname = request.form['firstname']
    lastname = request.form['lastname']
    email = request.form['email']

    if User.query.filter_by(username=username).first():
        return "OK"

    if User.query.filter_by(email=email).first():
        return "OK"
    
    db.session.close()

    user = User(
        username=username,
        email=email,
        password=password,
        date_joined=datetime.datetime.utcnow(),
        primary_group_id=4,
        notes=firstname + "<br>" + lastname,
        language='es'
    )
    
    user.save()

    #print "User created", firstname, lastname

    return "OK"

@csrf.exempt
@alfamas.route("/reset_password", methods=['PUT'])
def reset_password():

    username = request.form['username']
    password = request.form['password']

    user = User.query.filter_by(username=username).first()

    #db.session.close()

    user.password = password    
    user.save()

    return "OK"

@alfamas.route("/<int:forum_id>")
@alfamas.route("/<int:forum_id>-<slug>")
@login_required
#@allows.requires(CanAccessForum())
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(
        forum_id=forum_id, user=current_user
    )

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(
        forum_id=forum_instance.id, user=current_user, page=page,
        per_page=flaskbb_config["TOPICS_PER_PAGE"]
    )

    return render_template(
        "m_forum.html", forum=forum_instance,
        topics=topics, forumsread=forumsread,
    )

@alfamas.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@alfamas.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
@allows.requires(CanAccessTopic())
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    # Fetch some information about the topic
    topic = Topic.get_topic(topic_id=topic_id, user=current_user)

    # Count the topic views
    topic.views += 1
    topic.save()

    # fetch the posts in the topic
    posts = Post.query.\
        join(User, Post.user_id == User.id).\
        filter(Post.topic_id == topic.id).\
        add_entity(User).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated:
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)

    form = None
    if Permission(CanPostReply):
        form = QuickreplyForm()
        if form.validate_on_submit():
            post = form.save(current_user, topic)
            return view_post(post.id)

    return render_template("m_topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)

@alfamas.route("/post/<int:post_id>")
@login_required
def view_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    count = post.topic.post_count
    page = count / flaskbb_config["POSTS_PER_PAGE"]

    if count > flaskbb_config["POSTS_PER_PAGE"]:
        page += 1
    else:
        page = 1

    return redirect('/alfamas'+post.topic.url + "?page=%d#pid%s" % (page, post.id))


@alfamas.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@alfamas.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])
@login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    print "new_topic"
    if not Permission(CanPostTopic):
        flash(_("You do not have the permissions to create a new topic."),
              "danger")
        return redirect('/alfamas'+forum_instance.url)

    print "NewTopicForm"
    form = NewTopicForm()
    if request.method == "POST":
        if "preview" in request.form and form.validate():
            print "preview"
            return render_template(
                "m_new_topic.html", forum=forum_instance,
                form=form, preview=form.content.data
            )
        if "submit" in request.form and form.validate():
            print "submit"
            topic = form.save(current_user, forum_instance)
            # redirect to the new topic
            return redirect(url_for('alfamas.view_topic', topic_id=topic.id))

    print "render"
    return render_template(
        "m_new_topic.html", forum=forum_instance, form=form
    )


@alfamas.route("/topic/<int:topic_id>/delete", methods=["POST"])
@alfamas.route("/topic/<int:topic_id>-<slug>/delete", methods=["POST"])
@login_required
def delete_topic(topic_id=None, slug=None):
    print "delete_topic"
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(CanDeleteTopic):
        print "no_permission"
        flash(_("You do not have the permissions to delete this topic."),
              "danger")
        return redirect('/alfamas'+topic.forum.url)

    print "cant delete"
    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    print "delete and redirect to "
    print redirect(url_for("alfamas.view_forum", forum_id=topic.forum_id))
    return redirect(url_for("alfamas.view_forum", forum_id=topic.forum_id))


@alfamas.route("/topic/<int:topic_id>/lock", methods=["POST"])
@alfamas.route("/topic/<int:topic_id>-<slug>/lock", methods=["POST"])
@login_required
def lock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to lock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@alfamas.route("/topic/<int:topic_id>/unlock", methods=["POST"])
@alfamas.route("/topic/<int:topic_id>-<slug>/unlock", methods=["POST"])
@login_required
def unlock_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to unlock this topic."),
              "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@alfamas.route("/topic/<int:topic_id>/highlight", methods=["POST"])
@alfamas.route("/topic/<int:topic_id>-<slug>/highlight", methods=["POST"])
@login_required
def highlight_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to highlight this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = True
    topic.save()
    return redirect(topic.url)


@alfamas.route("/topic/<int:topic_id>/trivialize", methods=["POST"])
@alfamas.route("/topic/<int:topic_id>-<slug>/trivialize", methods=["POST"])
@login_required
def trivialize_topic(topic_id=None, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # Unlock is basically the same as lock
    if not Permission(IsAtleastModeratorInForum(forum=topic.forum)):
        flash(_("You do not have the permissions to trivialize this topic."),
              "danger")
        return redirect(topic.url)

    topic.important = False
    topic.save()
    return redirect(topic.url)

alfamas/templates/category.html
{% set page_title = category.title %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}
{% block content %}

<div class="index-view">
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li class="active">{{ category.title }}</li>
    </ol>

    {% include theme("forum/category_layout.html") %}
</div>

{% endblock %}

alfamas/templates/index.html
{% extends theme("layout.html") %}
{% block content %}

<div class="index-view">
    {% for category, forums in categories %}
        {% include theme("forum/category_layout.html") %}
    {% endfor %}

    <div class="panel page-panel">
        <div class="panel-heading page-head">
            {% trans %}Board Statistics{% endtrans %}
            [<a href="{{ url_for('forum.who_is_online') }}" onclick="window.open(this.href, 'wio_window','width=500,height=500'); return false;">{% trans %}Who is online?{% endtrans %}</a>]
        </div>
        <div class="panel-body page-body">
            <div class="row page-row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <p class="flaskbb-stats">{% trans %}Total number of registered users{% endtrans %}: <strong>{{ user_count }}</strong></p>
                    <p class="flaskbb-stats">{% trans %}Total number of topics{% endtrans %}: <strong>{{ topic_count }}</strong></p>
                    <p class="flaskbb-stats">{% trans %}Total number of posts{% endtrans %}: <strong>{{ post_count }}</strong></p>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <p class="flaskbb-stats">{% trans %}Newest registered user{% endtrans %}: {% if newest_user %}<a href="{{ newest_user.url }}">{{ newest_user.username }}</a>{% else %}{% trans %}No users{% endtrans %}{% endif %}</p>
                    <p class="flaskbb-stats">{% trans %}Registered users online{% endtrans %}: <strong>{{ online_users }}</strong></p>
                    {% if config["REDIS_ENABLED"] %}
                    <p class="flaskbb-stats">{% trans %}Guests online{% endtrans %}: <strong>{{ online_guests }}</strong></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

alfamas/templates/m_forum.html
{% set page_title = forum.title %}
{% set active_forum_nav=True %}

{% extends "m_layout.html" %}
{% block content %}
{% from theme('macros.html') import render_pagination, topic_pages %}

<div class="forum-view">

    <div class="row controls-row">
        <div class="pull-left">
            {{ render_pagination(topics, forum.url) }}
        </div> <!-- end span pagination -->

        {% if current_user|post_topic(forum) %}
        <div class="pull-right">
            {% if forum.locked %}
            <span class="btn btn-primary">
                <span class="fa fa-lock"></span> {% trans %}Locked{% endtrans %}
            </span>
            {% else %}
            <a href="{{ url_for('alfamas.new_topic', forum_id=forum.id, slug=forum.slug) }}" class="btn btn-primary">
                <span class="fa fa-pencil"></span> {% trans %}New Topic{% endtrans %}
            </a>
            {% endif %}
        </div>
        {% endif %}
    </div>

    <div class="panel forum-panel">
        <div class="panel-heading forum-head">
            <a href="{{ url_for('alfamas.view_forum', forum_id=forum.id, slug=forum.slug) }}">{{ forum.title }}</a>
        </div>

        <div class="panel-body forum-body">
            <div class="forum-meta">
                <div class="col-md-5 col-sm-5 col-xs-8 topic-name">{% trans %}Topic{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Posts{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Views{% endtrans %}</div>
                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">{% trans %}Last Post{% endtrans %}</div>
            </div>

            {% for topic, topicread in topics.items %}
            <div class="row forum-row hover clearfix">

                <div class="col-md-5 col-sm-5 col-xs-8 topic-info">
                    <div class="row">
                        <div class="col-md-1 col-sm-2 col-xs-2 topic-status">
                        {% if topic.locked %}
                            <span class="fa fa-lock topic-locked"></span>
                        {% elif topic.important %}
                            {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                                <span class="fa fa-star topic-starred-unread"></span>
                            {% else %}
                                <span class="fa fa-star-o topic-starred-read"></span>
                            {% endif %}
                        {% else %}
                            {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                                <span class="fa fa-comment topic-unread"></span>
                            {% else %}
                                <span class="fa fa-comment-o topic-read"></span>
                            {% endif %}
                        {% endif %}
                        </div>
                        <div class="col-md-11 col-sm-10 col-xs-10">
                            <div class="topic-name">
                                <a href="{{ url_for('alfamas.view_topic', topic_id=topic.id) }}">{{ topic.title }}</a>
                                <!-- Topic Pagination -->
                                <span class="topic-pages">{{ topic_pages(topic, flaskbb_config["POSTS_PER_PAGE"]) }}</span>
                            </div>

                            <div class="topic-author">
                                {% trans %}by{% endtrans %}
                                {% if topic.user_id %}
                                 <a href="#">{{ topic.user.username }}</a>
                                {% else %}
                                {{ topic.username }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.post_count }}
                </div>

                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.views }}
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">
                    <a href="{{ url_for('alfamas.view_post', post_id=topic.last_post.id) }}">{{ topic.last_post.date_created|time_since }}</a><br />

                    <div class="topic-author">
                        {% trans %}by{% endtrans %}
                        {% if topic.last_post.user_id %}
                        <a href="#">{{ topic.last_post.user.username }}</a>
                        {% else %}
                        {{ topic.last_post.username }}
                        {% endif %}
                    </div>
                </div>

            </div>  <!-- end forum-row -->
            {% else %}
            <div class="row forum-row clearfix">
                <div class="col-md-12 col-sm-12 co-xs-12">
                    {% trans %}No Topics.{% endtrans %}
                </div>
            </div> <!-- end forum-row -->
            {% endfor %}
        </div>
    </div>

    {% if current_user|can_moderate(forum) %}
    <div class="row controls-row">
        <a class="btn btn-default" href="{{ url_for('forum.manage_forum', forum_id=forum.id, slug=forum.slug) }}">
            <span class="fa fa-tasks"></span> {% trans %}Moderation Mode{% endtrans %}
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
    <script>
    $('.pagination a[href!=#]').each(function(index, link) {
        var $link = $(link);
        var href = $link.attr('href');
        href = href.replace("/forum/", "/alfamas/");

        $link.attr('href', href);

        console.debug(href);
    });
    </script>
{% endblock %}

alfamas/templates/m_topic.html
{% extends "m_layout.html" %}
{% set page_title = _("%(title)s - Topic", title=topic.title) %}
{% set active_forum_nav=True %}

{% block content %}
{% from theme('macros.html') import render_pagination, form_field, generate_post_id, generate_post_url %}

<div class="topic-view">

    {% include theme('m_topic_controls.html') %}

    <div class="panel topic-panel">
        <div class="panel-heading topic-head">
            <a href="{{ url_for('alfamas.view_topic', topic_id=topic.id) }}">{{ topic.title }}</a>
        </div>
        <div class="panel-body topic-body">
            {% for post, user in posts.items %}
            <div id="{{ post.id }}" class="row post-row clearfix">

                <div class="author col-md-2 col-sm-3 col-xs-12">
                    <!-- Registered User -->
                    {% if post.user_id %}
                    <div class="author-name"><h4><a href="#">{{ user.username }}</a></h4></div>

                    <!-- check if user is online or not -->
                    {% if user|is_online %}
                    <div class="author-online" data-toggle="tooltip" data-placement="top" title="online"></div>
                    {% else %}
                    <div class="author-offline" data-toggle="tooltip" data-placement="top" title="offline"></div>
                    {% endif %}
                    <div class="author-title"><h5>{{ user.primary_group.name }}</h5></div>

                    {% if user.avatar %}
                        <div class="author-avatar"><img src="{{ user.avatar }}" alt="avatar"></div>
                    {% endif %}

                    <div class="author-registered">{% trans %}Joined{% endtrans %}: {{ user.date_joined|format_date('%b %d %Y') }}</div>
                    <div class="author-posts">{% trans %}Posts{% endtrans %}: {{ user.post_count }}</div>
                    
                    {% if user.website %}
                    <div class="author-website"><a href="{{ user.website }}" rel="nofollow">{% trans %}Website{% endtrans %}</a></div>
                    {% endif %}

                    {% else %}
                    <!-- user deleted or guest -->
                    <div class="author-name"><h4><a href="{{ user.url }}">{{ post.username }}</a></h4></div>
                    <div class="author-title"><h5>{% trans %}Guest{% endtrans %}</h5></div>
                    {% endif %}

                </div>

                <div class="post-box col-md-10 col-sm-9 col-xs-12">

                    <div class="post-meta clearfix">
                        <div class="pull-left">
                            <!-- Creation date / Date modified -->
                            <a href="#">
                                {{ post.date_created|format_date('%d %B %Y - %H:%M') }}
                            </a>
                            {% if post.user_id and post.date_modified %}
                            <small>
                                (Last modified: {{ post.date_modified|format_date('%d %B %Y - %H:%M') }} by
                                <a href="#">{{ post.modified_by }}</a>.)
                            </small>
                            {% endif %}
                        </div>

                        <!-- Post number -->
                        <div class="pull-right">
                            <strong>#{{ generate_post_id(posts, loop.index, flaskbb_config["POSTS_PER_PAGE"]) }}</strong>
                        </div>
                    </div>

                        <div class="post-content clearfix" id="pid{{ post.id }}">
                        {{ post.content|markup|safe }}
                        <!-- Signature Begin -->
                        {% if flaskbb_config["SIGNATURE_ENABLED"] and post.user_id and user.signature %}
                        <div class="post-signature hidden-xs">
                        <hr />
                            {{ user.signature|markup|safe }}
                        </div>
                        {% endif %}
                        <!-- Signature End -->
                    </div>

                        <div class="post-footer clearfix">

                            <!-- Report/Edit/Delete/Quote Post-->
                            <div class="post-menu pull-right">

                            {% if current_user|post_reply(topic) %}
                            <!-- Quick quote -->
                                <a href="#" class="btn btn-icon icon-reply quote-btn" data-post-id="{{ post.id }}" data-toggle="tooltip" data-placement="top" title="Quote this post"></a>
                            <!-- Full quote/reply -->
                                <a href="{{ url_for('alfamas.reply_post', topic_id=topic.id, post_id=post.id) }}" class="btn btn-icon icon-replyall" data-toggle="tooltip" data-placement="top" title="Full Reply"></a>
                            {% endif %}

                            {% if current_user|edit_post(post) %}
                            <!-- Edit Post -->
                            <a href="{{ url_for('alfamas.edit_post', post_id=post.id) }}" class="btn btn-icon icon-edit" data-toggle="tooltip" data-placement="top" title="Edit this post"></a>
                            {% endif %}
                            {% if topic.first_post_id == post.id %}
                                {% if current_user|delete_topic(topic) %}
                                <form class="inline-form" method="post" action="{{ url_for('alfamas.delete_topic', topic_id=topic.id, slug=topic.slug) }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                    <button class="btn btn-icon icon-delete" data-toggle="tooltip" data-placement="top" title="Delete this topic"></button>
                                </form>
                                {% endif %}
                            {% else %}
                                {% if current_user|delete_post(post) %}
                            <!-- Delete Post -->
                                <form class="inline-form" method="post" action="{{ url_for('alfamas.delete_post', post_id=post.id) }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                                    <button  class="btn btn-icon icon-delete" data-toggle="tooltip" data-placement="top" title="Delete this post"></button>
                                </form>
                                {% endif %}

                            {% endif %}
                            </div> <!-- end post-menu -->
                        </div> <!-- end footer -->

                </div>
            </div>
            {% endfor %}

        </div> <!-- end topic-body -->
    </div> <!-- end topic-panel -->

    {% include theme('m_topic_controls.html') %}
    {% from theme("macros.html") import render_field, render_quickreply, render_submit_field %}
    {% if form %}
    <form class="form" action="#" method="post">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col-md-offset-2 col-sm-offset-3 col-md-10 col-sm-9 col-xs-12">
                <div class="editor-box">
                    <div class="editor quickreply">
                            {{ render_quickreply(form.content, div_class="new-message", rows=7, cols=75, placeholder="", **{'data-provide': 'markdown', 'data-autofocus': 'false', 'class': 'flaskbb-editor'}) }}
                    </div>
                    <div class="editor-submit">
                        {{ render_submit_field(form.submit, input_class="btn btn-success pull-right") }}
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% include theme('editor_help.html') %}
    {% endif %}

</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/editor.min.js') }}"></script>

    <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

    $('.pagination a[href!=#]').each(function(index, link) {
        var $link = $(link);
        var href = $link.attr('href');
        $link.attr('href', '/alfamas'+href);
    });
    </script>
{% endblock %}

alfamas/templates/m_topic_controls.html
<div class="row controls-row">
    <div class ="col-md-6 col-sm-6 col-xs-12 controls-col">
        <div class="pull-left">
            {{ render_pagination(posts, topic.url) }}
        </div>
    </div> <!-- end span pagination -->

{% if current_user.is_authenticated %}
    <div class="col-md-6 col-sm-6 col-xs-12 controls-col">
        <div class="pull-right">
            {% if current_user|can_moderate(topic.forum) or current_user|delete_topic(topic)%}
            <!-- Moderation buttons -->
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-bars" aria-hidden="true"></span> {% trans %}Moderate{% endtrans %} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">

                {% if current_user|delete_topic(topic) %}
                <li>
                    <form class="inline-form" method="post" action="{{ url_for('alfamas.delete_topic', topic_id=topic.id, slug=topic.slug) }}">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button class="btn btn-link">
                            <span class="fa fa-trash-o"></span> {% trans %}Delete Topic{% endtrans %}
                        </button>
                    </form>
                </li>
                {% endif %}

                {% if current_user|can_moderate(topic.forum) %}
                    {% if not topic.locked %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('alfamas.lock_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-lock"></span> {% trans %}Lock Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% else %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('alfamas.unlock_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-unlock"></span> {% trans %}Unlock Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% endif %}

                    {% if not topic.important %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('alfamas.highlight_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-star"></span> {% trans %}Highlight Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% else %}
                    <li>
                        <form class="inline-form" method="post" action="{{ url_for('alfamas.trivialize_topic', topic_id=topic.id, slug=topic.slug) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button class="btn btn-link">
                                <span class="fa fa-star-o"></span> {% trans %}Trivialize Topic{% endtrans %}
                            </button>
                        </form>
                    </li>
                    {% endif %}
                {% endif %}
                </ul>
            </div>
            <!-- end Moderation buttons -->
            {% endif %}

            {% if current_user.is_tracking_topic(topic) %}
            <form class="inline-form" method="post" action="{{ url_for('alfamas.untrack_topic', topic_id=topic.id, slug=topic.slug) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-default">
                    <span class="fa fa-tag" aria-hidden="true"></span> {% trans %}Untrack Topic{% endtrans %}
                </button>
            </form>
            {% else %}
            <!--
            <form class="inline-form" method="post" action="{{ url_for('alfamas.track_topic', topic_id=topic.id, slug=topic.slug) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button class="btn btn-default">
                    <span class="fa fa-tag" aria-hidden="true"></span> {% trans %}Track Topic{% endtrans %}
                </button>
            </form>
            -->
            {% endif %}

            {% if current_user|post_reply(topic) %}
            <a href="{{ url_for('alfamas.new_post', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-primary">
                <span class="fa fa-pencil"></span> {% trans %}Reply{% endtrans %}
            </a>
            {% else %}
            <div class="btn btn-primary"><span class="fa fa-lock"></span> {% trans %}Locked{% endtrans %}</div>
            {% endif %}
        </div>
    </div>
{% endif %} {# end current_user.is_authenticated #}
</div>